Experiment 'pythonaa' is active
Experiment 'pythonTensorboardExperiment' is active
Experiment 'PythonPyTorchProfiler' is active
Experiment 'pythonDeprecatePythonPath' is active
Experiment 'pythonRunFailedTestsButtonDisplayed' is active
Experiment 'pythonRefreshTestsButtonDisplayed' is active
Experiment 'pythonRememberDebugConfig' is active
Error 2021-12-08 22:49:57: Failed to initialize source map support in extension
> conda info --json
> C:\ProgramData\Miniconda3\python.exe ~\Documents\Git\VSCode_Portable\VSCode-win32-x64-1.62.3\data\extensions\ms-python.python-2021.11.1422169775\pythonFiles\interpreterInfo.py
> "C:\Program Files\Inkscape\bin\python.exe" ~\Documents\Git\VSCode_Portable\VSCode-win32-x64-1.62.3\data\extensions\ms-python.python-2021.11.1422169775\pythonFiles\interpreterInfo.py
> ~\Documents\Git\VSCode_Portable\python-3.10.1-embed-amd64\python.exe -c "import sys;print(sys.executable)"
> ~\Documents\Git\VSCode_Portable\python-3.10.1-embed-amd64\python.exe -c "import sys;print(sys.executable)"
> ~\Documents\Git\VSCode_Portable\python-3.10.1-embed-amd64\python.exe -c "import sys;print(sys.executable)"
> ~\Documents\Git\VSCode_Portable\python-3.10.1-embed-amd64\python.exe -c "import sys;print(sys.executable)"
> ~\AppData\Local\Programs\Python\Python39\python.exe ~\Documents\Git\VSCode_Portable\VSCode-win32-x64-1.62.3\data\extensions\ms-python.python-2021.11.1422169775\pythonFiles\interpreterInfo.py
> ~\Documents\Git\VSCode_Portable\python-3.10.1-embed-amd64\python.exe -c "import sys;print(sys.executable)"
Starting Pylance language server.
> ~\Documents\Git\VSCode_Portable\python-3.10.1-embed-amd64\python.exe -c "import sys;print(sys.executable)"
Error 2021-12-08 22:49:59: Diagnostic Code: InvalidPythonInterpreterDiagnostic, Message: No Python interpreter is selected. You need to select a Python interpreter to enable features such as IntelliSense, linting, and debugging.
Diagnostic Code: InvalidPythonInterpreterDiagnostic, Message: No Python interpreter is selected. You need to select a Python interpreter to enable features such as IntelliSense, linting, and debugging.
> "C:/ProgramData/Miniconda3/Scripts/activate && conda activate base && echo 'e8b39361-0157-4923-80e1-22d70d46dee6' && python c:/Users/Racarla/Documents/Git/VSCode_Portable/VSCode-win32-x64-1.62.3/data/extensions/ms-python.python-2021.11.1422169775/pythonFiles/printEnvVariables.py"
> "C:/ProgramData/Miniconda3/Scripts/activate && conda activate base && echo 'e8b39361-0157-4923-80e1-22d70d46dee6' && python c:/Users/Racarla/Documents/Git/VSCode_Portable/VSCode-win32-x64-1.62.3/data/extensions/ms-python.python-2021.11.1422169775/pythonFiles/printEnvVariables.py"
> C:\ProgramData\Miniconda3\python.exe -c "import pip"
Error 2021-12-08 22:50:39: Error in installing the module 'ipykernel', Error: Command failed with errors, check the terminal for details. Command: conda install -c conda-forge --name base ipykernel -y
Traceback (most recent call last):
  File "c:\Users\Racarla\Documents\Git\VSCode_Portable\VSCode-win32-x64-1.62.3\data\extensions\ms-python.python-2021.11.1422169775\pythonFiles\shell_exec.py", line 26, in <module>
    subprocess.check_call(shell_args, stdout=sys.stdout, stderr=sys.stderr)
  File "C:\ProgramData\Miniconda3\lib\subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['conda', 'install', '-c', 'conda-forge', '--name', 'base', 'ipykernel', '-y']' returned non-zero exit status 1.

> C:\ProgramData\Miniconda3\python.exe -c "import ipykernel"
Error 2021-12-08 22:56:55: Error while running worker[Worker 2]. undefined
Error 2021-12-08 22:56:55: Error while running worker[Worker 1]. undefined
Error 2021-12-08 22:56:55: Failed to activate a workspace, Class name = m, completed in 418037ms, has a falsy return value, Arg 1: <Uri:c:\Users\Racarla\Documents\Git\VSCode_Portable\Projects\ButterworthFilter>, Return Value: undefined [Canceled: Canceled
	at Object.i [as canceled] (c:\Users\Racarla\Documents\Git\VSCode_Portable\VSCode-win32-x64-1.62.3\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:5:1157)
	at c:\Users\Racarla\Documents\Git\VSCode_Portable\VSCode-win32-x64-1.62.3\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:98:9064
	at Array.forEach (<anonymous>)
	at n.dispose (c:\Users\Racarla\Documents\Git\VSCode_Portable\VSCode-win32-x64-1.62.3\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:98:9012)
	at b.terminate (c:\Users\Racarla\Documents\Git\VSCode_Portable\VSCode-win32-x64-1.62.3\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:103:694)
	at o (c:\Users\Racarla\Documents\Git\VSCode_Portable\VSCode-win32-x64-1.62.3\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:113:32681)
	at Socket.<anonymous> (c:\Users\Racarla\Documents\Git\VSCode_Portable\VSCode-win32-x64-1.62.3\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:113:30296)
	at Socket.emit (events.js:327:22)
	at Socket.EventEmitter.emit (domain.js:467:12)
	at Pipe.<anonymous> (net.js:673:12)]
Error 2021-12-08 22:56:55: Failure during activation. [Canceled: Canceled
	at Object.i [as canceled] (c:\Users\Racarla\Documents\Git\VSCode_Portable\VSCode-win32-x64-1.62.3\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:5:1157)
	at c:\Users\Racarla\Documents\Git\VSCode_Portable\VSCode-win32-x64-1.62.3\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:98:9064
	at Array.forEach (<anonymous>)
	at n.dispose (c:\Users\Racarla\Documents\Git\VSCode_Portable\VSCode-win32-x64-1.62.3\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:98:9012)
	at b.terminate (c:\Users\Racarla\Documents\Git\VSCode_Portable\VSCode-win32-x64-1.62.3\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:103:694)
	at o (c:\Users\Racarla\Documents\Git\VSCode_Portable\VSCode-win32-x64-1.62.3\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:113:32681)
	at Socket.<anonymous> (c:\Users\Racarla\Documents\Git\VSCode_Portable\VSCode-win32-x64-1.62.3\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:113:30296)
	at Socket.emit (events.js:327:22)
	at Socket.EventEmitter.emit (domain.js:467:12)
	at Pipe.<anonymous> (net.js:673:12)]
Error 2021-12-08 22:56:55: sendStartupTelemetry() failed. [Canceled: Canceled
	at Object.i [as canceled] (c:\Users\Racarla\Documents\Git\VSCode_Portable\VSCode-win32-x64-1.62.3\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:5:1157)
	at c:\Users\Racarla\Documents\Git\VSCode_Portable\VSCode-win32-x64-1.62.3\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:98:9064
	at Array.forEach (<anonymous>)
	at n.dispose (c:\Users\Racarla\Documents\Git\VSCode_Portable\VSCode-win32-x64-1.62.3\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:98:9012)
	at b.terminate (c:\Users\Racarla\Documents\Git\VSCode_Portable\VSCode-win32-x64-1.62.3\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:103:694)
	at o (c:\Users\Racarla\Documents\Git\VSCode_Portable\VSCode-win32-x64-1.62.3\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:113:32681)
	at Socket.<anonymous> (c:\Users\Racarla\Documents\Git\VSCode_Portable\VSCode-win32-x64-1.62.3\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:113:30296)
	at Socket.emit (events.js:327:22)
	at Socket.EventEmitter.emit (domain.js:467:12)
	at Pipe.<anonymous> (net.js:673:12)]
